-- !Ups

create table message (
  id bigint generated by default as identity not null,
  name varchar(100) not null,
  mail varchar(255),
  message varchar(255),
  postdate timestamp not null,
  constraint pk_message primary key (id)
);

-- !Downs

drop table if exists message;
